### ISSUE TITLE
taxon identifier mapping not correct for at least silva database

### ISSUE THREAD

**Issue by deborah-chasman** [Ong-Research/microbiome-pipeline#11]
I was processing stool samples and noticed that only minikraken labeled any ASVs as Bifidobacterium. It's very unexpected that the other databases would miss this.

Let's start with Silva as an example.
The kraken_taxatable.qs file for minikraken identifies asv_1 as Genus Bifidobacterium.
Meanwhile, the kraken_taxatable.qs file for silva says this ASV is Manitoban Elk. ???

I think something happened during ID mapping. Perhaps minikraken is using NCBI identifiers for taxa but silva and the other databases are using something else?

**Comment by deborah-chasman** [comment]
I addressed this by writing another script to generate the ID mapping from Kraken output: https://github.com/Ong-Research/microbiome-pipeline/pull/14

**Comment by deborah-chasman** [comment]
This affects any database that doesn't use NCBI identifiers.

**Comment by welch16** [comment]
I am going to close the issue, because you already fixed this in #14 and #15,

Thanks!
